"""Build the static FMR dashboard's data bundle.

Aggregates every JSON artifact under an outputs dir — the mock snapshot in
``fmr/outputs/`` plus any real-model snapshots in ``fmr/outputs/real/<dataset>/``
— into ``fmr/dashboard/data.js`` (`window.FMR_DATA`). The dashboard is fully
static (no server, no build step, no CDN): opening ``fmr/dashboard/index.html``
reads this bundle directly, so it works from ``file://``, GitHub Pages, or any
static host, and it updates automatically the moment a Colab run pushes real
results (just re-run this script, or it is re-run in the notebook).

Records are trimmed (capped count, only explorer-relevant fields) to keep the
bundle small enough to load instantly.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]         # fmr/
_DASH = _ROOT / "dashboard"
_ARTIFACTS = ("baselines", "blind_test", "fmr_results", "full_benchmark", "ablations")
_RECORD_FIELDS = (
    "sample_id", "modality", "question", "gt_answer", "steps_text", "answer",
    "correct", "signal_a", "signal_b", "signal_c", "fs", "fs_per_step",
    "confidence", "n_steps", "iou_mean", "grounded_latent",
)


def _load(path: Path):
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # corrupt / partial file -> skip, don't crash the build
        print(f"[dashboard] warn: could not read {path}: {exc}")
        return None


def _trim_records(recs_path: Path, cap: int = 300) -> list | None:
    data = _load(recs_path)
    if not data:
        return None
    test = data.get("test", []) if isinstance(data, dict) else []
    out = []
    for r in test[:cap]:
        out.append({k: r.get(k) for k in _RECORD_FIELDS})
    return out


def _threshold_for(fmr_results: dict | None) -> float | None:
    """The calibrated FS abstention threshold (so the explorer can label ANSWER/ABSTAIN)."""
    if not fmr_results:
        return None
    ab = fmr_results.get("abstention", {})
    fs = ab.get("fs") or ab.get("fs_post_correction") or {}
    t = fs.get("threshold")
    return t if (t is not None and t != float("inf")) else None


def _collect_snapshot(d: Path, label: str, kind: str) -> dict | None:
    snap = {"label": label, "kind": kind}
    found = False
    for name in _ARTIFACTS:
        obj = _load(d / f"{name}.json")
        if obj is not None:
            snap[name] = obj
            found = True
    recs = _trim_records(d / "fmr_records.json")
    if recs is not None:
        snap["records"] = recs
        found = True
    status = _load(d / "run_status.json")
    if status is not None:
        snap["run_status"] = status
    integ = _load(d / "adapter_integration.json")
    if integ is not None:
        snap["adapter_integration"] = integ
    snap["fs_threshold"] = _threshold_for(snap.get("fmr_results"))
    return snap if found else None


def build(outputs_dir: str | Path = None) -> Path:
    out = Path(outputs_dir) if outputs_dir else (_ROOT / "outputs")
    sources: dict[str, dict] = {}

    mock = _collect_snapshot(out, "Mock (synthetic)", "mock")
    if mock:
        sources["mock"] = mock

    real_root = out / "real"
    if real_root.exists():
        for d in sorted(p for p in real_root.iterdir() if p.is_dir()):
            snap = _collect_snapshot(d, f"Real — {d.name}", "real")
            if snap:
                sources[f"real:{d.name}"] = snap

    # Top-level artifact spanning multiple sources (mock + real) in one file.
    abst = _load(out / "abstention_baselines.json")

    # Default to the most-populated real source (has fmr_results/records), so the
    # dashboard opens on a source that actually has the full pipeline to show —
    # not a real source that only ran baselines+blind.
    def _richness(s: dict) -> int:
        return sum(k in s for k in ("fmr_results", "records", "full_benchmark")) + (2 if s["kind"] == "real" else 0)
    default_source = max(sources, key=lambda k: _richness(sources[k])) if sources else None

    bundle = {
        "generated_at": _dt.datetime.now().isoformat(timespec="seconds"),
        "has_real": any(s["kind"] == "real" for s in sources.values()),
        "default_source": default_source,
        "sources": sources,
        "abstention_baselines": abst,   # {sources: {mock, real:vqa_rad, ...}}
    }

    _DASH.mkdir(parents=True, exist_ok=True)
    data_js = _DASH / "data.js"
    data_js.write_text(
        "// Auto-generated by scripts/make_dashboard.py — do not edit by hand.\n"
        "window.FMR_DATA = " + json.dumps(bundle, indent=1, default=str) + ";\n",
        encoding="utf-8",
    )
    kb = data_js.stat().st_size / 1024

    # Stamp a fresh version query on the asset URLs so a rebuild always forces the
    # browser to refetch data.js/app.js/style.css (defeats stale-cache — the one
    # dashboard footgun we keep hitting). Only the ?v=<epoch> changes.
    import re
    import time
    index = _DASH / "index.html"
    if index.exists():
        ver = int(time.time())
        html = index.read_text(encoding="utf-8")
        html = re.sub(r'(href="style\.css)(\?v=\d+)?"', rf'\1?v={ver}"', html)
        html = re.sub(r'(src="(?:data|app)\.js)(\?v=\d+)?"', rf'\1?v={ver}"', html)
        index.write_text(html, encoding="utf-8")

    print(f"[dashboard] wrote {data_js} ({kb:.0f} KB) — sources: {list(sources)}"
          f" | has_real={bundle['has_real']} | default={default_source}")
    return data_js


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None, help="outputs dir (default fmr/outputs)")
    args = ap.parse_args()
    build(args.out)
